### ISSUE TITLE
Structure of myvnf_vnfd.yaml ?

### ISSUE THREAD

**Issue by rohankharade** [AdamIsrael/vnfproxy#2]
Can you provide the structure of myvnf_vnfd.yaml file ?
Also have you tested it on which release ?
Does it work with OSM r4 ?

**Comment by AdamIsrael** [comment]
Hi Rohan,

You can find several examples of the VNFD in the OSM [devops repo](https://osm.etsi.org/gitweb/?p=osm/devops.git;a=tree;f=descriptor-packages/vnfd;h=9ebc54cf0453fc4f3c04eeb27c58fcad55c9a803;hb=HEAD). The descriptors should work with the most recent release (R4) as well as the forthcoming R5.

The vnfproxy charm layer is the underlying layer used by proxy charms within OSM, and is backwards compatible, working with R4 and R5.
